apiVersion: v1
name: kubeskoop-exporter
description: A Helm chart for KubeSkoop Exporter
type: application
version: 0.1.1
appVersion: 0.1.1
icon: https://img.shields.io/github/v/tag/alibaba/kubeskoop
keywords:
  - kubeskoop
  - kubeskoop-exporter
home: https://github.com/alibaba/kubeskoop
sources: 
  - https://github.com/alibaba/kubeskoop