image:
  repository: "registry.cn-hangzhou.aliyuncs.com/acs/kubeskoop-exporter"
  repositoryPre: "registry.cn-hangzhou.aliyuncs.com/build-test/kubeskoop-exporter"
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "v0.0.1-g857c8be-aliyun"

initcontainer:
  tag: latest
  pullPolicy: Always
  repository: registry.cn-hangzhou.aliyuncs.com/acs/btfhack

name: kubeskoop-exporter
namespace: kubeskoop
debugMode: false
runtimeEndpoint: /run/containerd/containerd.sock
appName: kubeskoop-exporter
preRelease: false

expose_labels:
  - source: ip
    type: meta
  - source: app
    type: label
    replace: component

resources: 
  limits:
    cpu: 500m
    memory: 1024Mi
  requests:
    cpu: 500m
    memory: 1024Mi

config:
  enableEventServer: true
  enableMetricServer: true
  remoteLokiAddress: "loki-service"
  metricLabelVerbose: true
  metricCacheInterval: 15
  metricServerPort: 9102
  metricProbes: ["netdev", "io","socketlatency","packetloss","net_softirq","tcpext","tcpsummary","tcp","sock","softnet","udp","virtcmdlatency","kernellatency"]
  eventProbes: ["tcpreset","packetloss"] 
  eventServerPort: 19102

nodeSelector: {}
  