name: kubeskoop-exporter
debugMode: false
runtimeEndpoint: /run/containerd/containerd.sock
appName: kubeskoop-exporter

image:
  repository: kubeskoop/kubeskoop
  # Overrides the image tag whose default is the chart appVersion.
  tag: latest
  imagePullPolicy: Always

initContainer:
  enabled: true
  repository: registry.cn-hangzhou.aliyuncs.com/acs/btfhack
  tag: latest
  imagePullPolicy: Always

expose_labels:
  - source: ip
    type: meta
  - source: app
    type: label
    replace: component

resources:
  limits:
    cpu: 500m
    memory: 1024Mi
  requests:
    cpu: 500m
    memory: 1024Mi

config:
  enableMetricServer: true
  metricLabelVerbose: true
  metricCacheInterval: 15
  metricServerPort: 9102
  metricProbes:
  - netdev
  - io
  - socketlatency
  - packetloss
  - net_softirq
  - tcpext
  - tcpsummary
  - tcp
  - sock
  - softnet
  - udp
  - virtcmdlatency
  - kernellatency

  enableEventServer: true
  eventServerPort: 19102
  remoteLokiAddress: loki-service.skoop.svc.cluster.local
  eventProbes:
  - tcpreset
  - packetloss

nodeSelector: {}
tolerations: {}
