apiVersion: v1
data:
  config.yaml: |-
    debugmode: {{ .Values.debugMode }}
    metric_config:
      interval: {{ .Values.config.metricCacheInterval }}
      port: {{ .Values.config.metricServerPort }}
      verbose: {{ .Values.config.metricLabelVerbose }}
      expose_labels:
      {{- with .Values.expose_labels }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      probes:{{- range .Values.config.metricProbes }}
      - {{ . }}{{- end }}
    event_config:
      port: {{ .Values.config.eventServerPort }}
      loki_enable: {{ .Values.config.enableEventServer }}
      loki_address: {{ .Values.config.remoteLokiAddress }}
      probes: {{- range .Values.config.eventProbes }}
      - {{ . }}{{- end }}
kind: ConfigMap
metadata:
  name: kubeskoop-config
  namespace: {{ .Release.Namespace }}
