apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.appName }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "9102"
        prometheus.io/scheme: http
        prometheus.io/scrape: "true"
      name: {{ .Values.appName }}
    spec:
      hostNetwork: true
      hostPID: true
      hostIPC: true
      dnsPolicy: ClusterFirstWithHostNet
      initContainers:
        - name: preparels

          image: "{{ .Values.initcontainer.repository }}:{{ .Values.initcontainer.tag }}"
          volumeMounts:
            - name: bpfdir
              mountPath: /etc/net-exporter/btf
            - mountPath: /boot/
              name: boot
          command: [btfhack, discover,-p ,/etc/net-exporter/btf/]
      containers:
      - image:  "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        name: inspector
        env:
        - name: INSPECTOR_NODENAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        volumeMounts:
          - name: configvolume
            mountPath: /etc/config/
          - name: bpfdir
            mountPath: /etc/net-exporter/btf
          - name: procfs
            mountPath: /proc
          - mountPath: /run/containerd/containerd.sock
            name: runtimeendpoint
          - mountPath: /var/run/
            name: rundir
          - mountPath: /sys/fs/bpf
            name: bpfmap
            mountPropagation: HostToContainer
          - mountPath: /sys/kernel/debug
            name: bpfdebugfs
            mountPropagation: HostToContainer
          - mountPath: /etc/node-hostname
            name: hostname
        command: [/bin/inspector,server]
        securityContext:
          privileged: true
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: procfs
          hostPath:
            path: /proc
        - name: runtimeendpoint
          hostPath:
            path: {{ .Values.runtimeEndpoint }}
        - name: boot
          hostPath:
            path: /boot/
        - name: rundir
          hostPath:
            path: /var/run/
        - hostPath:
            path: /sys/fs/bpf
            type: DirectoryOrCreate
          name: bpfmap
        - hostPath:
            path: /sys/kernel/debug
          name: bpfdebugfs
        - name: hostname
          hostPath:
            path: /etc/hostname
            type: FileOrCreate
        - name: configvolume
          configMap:
            name: kubeskoop-config
        - name: bpfdir
          emptyDir: {}