apiVersion: v1
name: kubeskoop
description: Promtheus exporter and kernel tracing for OS metrics in kubernetes, with pluggable metric collectors and kernel eBPF tracers.
type: application
annotations:
  category: Analytics
  licenses: Apache-2.0
version: 1.0.2
appVersion: 1.0.0-rc.1
icon: https://img.shields.io/github/v/tag/alibaba/kubeskoop
keywords:
  - kubeskoop
  - kubernetes
  - prometheus
  - eBPF
  - ebpf
  - monitoring
home: https://github.com/alibaba/kubeskoop
sources:
  - https://github.com/alibaba/kubeskoop
  - https://kubeskoop.io/
maintainers:
- name: KubeSkoop
  url: https://kubeskoop.io/
